// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: UI_test

#include "../ui.h"

void ui_main_screen_screen_init(void)
{
ui_main_screen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_main_screen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_hewwo = lv_label_create(ui_main_screen);
lv_obj_set_width( ui_hewwo, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_hewwo, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_hewwo, -3 );
lv_obj_set_y( ui_hewwo, 1 );
lv_obj_set_align( ui_hewwo, LV_ALIGN_CENTER );
lv_label_set_text(ui_hewwo,"hewwo :3");
lv_obj_clear_flag( ui_hewwo, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_scrollbar_mode(ui_hewwo, LV_SCROLLBAR_MODE_OFF);

ui_back2home = lv_btn_create(ui_main_screen);
lv_obj_set_width( ui_back2home, lv_pct(30));
lv_obj_set_height( ui_back2home, lv_pct(10));
lv_obj_set_x( ui_back2home, 0 );
lv_obj_set_y( ui_back2home, lv_pct(30) );
lv_obj_set_align( ui_back2home, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_back2home, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_scrollbar_mode(ui_back2home, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_style_border_color(ui_back2home, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_back2home, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_back2home, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_back2home, lv_color_hex(0x52AAFF), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_back2home, 255, LV_PART_MAIN| LV_STATE_CHECKED);

ui_goobye = lv_label_create(ui_back2home);
lv_obj_set_width( ui_goobye, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_goobye, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_goobye, lv_pct(0) );
lv_obj_set_y( ui_goobye, lv_pct(3) );
lv_obj_set_align( ui_goobye, LV_ALIGN_CENTER );
lv_label_set_text(ui_goobye,"goobye");
lv_obj_clear_flag( ui_goobye, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_scrollbar_mode(ui_goobye, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_style_text_color(ui_goobye, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_goobye, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_back2home, ui_event_back2home, LV_EVENT_ALL, NULL);

}
