// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: UI_test

#include "../ui.h"

void ui_start_screen_init(void)
{
    ui_start_screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_start_screen, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_bg = lv_img_create(ui_start_screen);
    lv_img_set_src(ui_bg, &ui_img_1_bg_png);
    lv_obj_set_width(ui_bg, lv_pct(100));
    lv_obj_set_height(ui_bg, lv_pct(100));
    lv_obj_clear_flag(ui_bg, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN); /// Flags
    lv_obj_set_scrollbar_mode(ui_bg, LV_SCROLLBAR_MODE_OFF);

    ui_mainlogo = lv_img_create(ui_start_screen);
    lv_img_set_src(ui_mainlogo, &ui_img_logo_png);
    lv_obj_set_width(ui_mainlogo, LV_SIZE_CONTENT);  /// 100
    lv_obj_set_height(ui_mainlogo, LV_SIZE_CONTENT); /// 100
    lv_obj_set_x(ui_mainlogo, 0);
    lv_obj_set_y(ui_mainlogo, lv_pct(-2));
    lv_obj_set_align(ui_mainlogo, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_mainlogo, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN); /// Flags

    ui_development_label = lv_label_create(ui_start_screen);
    lv_obj_set_x(ui_development_label, 4);
    lv_obj_set_y(ui_development_label, 5);
    lv_label_set_text(ui_development_label, "Under Development v0.0.1");
    lv_obj_clear_flag(ui_development_label, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN); /// Flags
    lv_obj_set_scrollbar_mode(ui_development_label, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_text_color(ui_development_label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_development_label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_development_label, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_init_button = lv_btn_create(ui_start_screen);
    lv_obj_set_width(ui_init_button, 100);
    lv_obj_set_height(ui_init_button, 40);
    lv_obj_set_x(ui_init_button, 0);
    lv_obj_set_y(ui_init_button, lv_pct(30));
    lv_obj_set_align(ui_init_button, LV_ALIGN_CENTER);
    lv_obj_add_style(ui_init_button, &ui_btndefstyle, LV_STATE_FOCUS_KEY);

    ui_welcome_text = lv_label_create(ui_init_button);
    lv_obj_set_width(ui_welcome_text, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_welcome_text, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_welcome_text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_welcome_text, "Welcome");
    lv_obj_clear_flag(ui_welcome_text, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN); /// Flags
    lv_obj_set_scrollbar_mode(ui_welcome_text, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_border_color(ui_welcome_text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_opa(ui_welcome_text, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_width(ui_welcome_text, 1, LV_PART_MAIN | LV_STATE_PRESSED);

    // Create btn group
    ui_grp_init_button = lv_group_create();
    lv_group_add_obj(ui_grp_init_button, ui_init_button);

    lv_obj_add_event_cb(ui_init_button, ui_event_init_button, LV_EVENT_ALL, NULL);
}

// Set indevs to whatever group it has to be
void ui_start_screen_setindev(lv_group_t *group)
{
    lv_indev_set_group(indev_joystick, group);
    lv_indev_set_group(indev_button, group);
}

// Handle init button being clicked/pressed
void ui_event_init_button(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    // Check if event is click
    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_screen_change(&ui_main_screen, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_main_screen_init);
        ui_main_screen_setindev(ui_grp_btnmatrix);
        _ui_screen_delete(&ui_start_screen);
    }
    // Check if event is key (SEL)
    else if (event_code == LV_EVENT_KEY)
    {
        if (lv_indev_get_key(indev_button) == LV_KEY_ENTER)
        {
            _ui_screen_change(&ui_main_screen, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_main_screen_init);
            ui_main_screen_setindev(ui_grp_btnmatrix);
            _ui_screen_delete(&ui_start_screen);
        }
    }
}