// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: UI_test

#include "../ui.h"

void ui_start_screen_screen_init(void)
{
    ui_start_screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_start_screen, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_bg = lv_img_create(ui_start_screen);
    lv_img_set_src(ui_bg, &ui_img_1_bg_png);
    lv_obj_set_width(ui_bg, lv_pct(100));
    lv_obj_set_height(ui_bg, lv_pct(100));
    lv_obj_clear_flag(ui_bg, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN); /// Flags
    lv_obj_set_scrollbar_mode(ui_bg, LV_SCROLLBAR_MODE_OFF);

    ui_mainlogo = lv_img_create(ui_start_screen);
    lv_img_set_src(ui_mainlogo, &ui_img_logo_png);
    lv_obj_set_width(ui_mainlogo, LV_SIZE_CONTENT);  /// 100
    lv_obj_set_height(ui_mainlogo, LV_SIZE_CONTENT); /// 100
    lv_obj_set_x(ui_mainlogo, 0);
    lv_obj_set_y(ui_mainlogo, lv_pct(-2));
    lv_obj_set_align(ui_mainlogo, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_mainlogo, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN); /// Flags

    ui_development_label = lv_label_create(ui_start_screen);
    lv_obj_set_x(ui_development_label, 4);
    lv_obj_set_y(ui_development_label, 5);
    lv_label_set_text(ui_development_label, "Under Development v0.1");
    lv_obj_clear_flag(ui_development_label, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN); /// Flags
    lv_obj_set_scrollbar_mode(ui_development_label, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_text_color(ui_development_label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_development_label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_development_label, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_init_button1 = lv_btn_create(ui_start_screen);
    lv_obj_set_width(ui_init_button1, 100);
    lv_obj_set_height(ui_init_button1, 40);
    lv_obj_set_x(ui_init_button1, 0);
    lv_obj_set_y(ui_init_button1, lv_pct(30));
    lv_obj_set_align(ui_init_button1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_init_button1, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN); /// Flags
    lv_obj_set_scrollbar_mode(ui_init_button1, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_bg_color(ui_init_button1, lv_color_hex(0x3044FA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_init_button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_init_button1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_init_button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_init_button1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_init_button1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_init_button1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_init_button1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_init_button1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_init_button1, lv_color_hex(0x3044FA), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_init_button1, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_init_button1, lv_color_hex(0x000AC2), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_init_button1, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_color(ui_init_button1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_opa(ui_init_button1, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_width(ui_init_button1, 3, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_side(ui_init_button1, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_welcome_text1 = lv_label_create(ui_init_button1);
    lv_obj_set_width(ui_welcome_text1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_welcome_text1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_welcome_text1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_welcome_text1, "Welcome");
    lv_obj_clear_flag(ui_welcome_text1, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN); /// Flags
    lv_obj_set_scrollbar_mode(ui_welcome_text1, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_border_color(ui_welcome_text1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_opa(ui_welcome_text1, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_width(ui_welcome_text1, 1, LV_PART_MAIN | LV_STATE_PRESSED);

    lv_obj_add_event_cb(ui_init_button1, ui_event_init_button1, LV_EVENT_ALL, NULL);
}
