// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: UI_test

#ifndef _UI_TEST_UI_H
#define _UI_TEST_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"

// SCREEN: ui_start_screen
void ui_start_screen_screen_init(void);
void ui_event_init_button1( lv_event_t * e);

extern lv_obj_t *ui_start_screen;
extern lv_obj_t *ui_bg;
extern lv_obj_t *ui_main_logo;
extern lv_obj_t *ui_development_label;
extern lv_obj_t *ui_init_button1;
extern lv_obj_t *ui_welcome_text1;

// SCREEN: ui_main_screen
void ui_main_screen_screen_init(void);
void ui_event_returntostart( lv_event_t * e);

extern lv_obj_t *ui_main_screen;
extern lv_obj_t *ui_returntostart;
extern lv_obj_t *ui_mainpanel;

// Button matrix stuff
extern lv_obj_t *buttonmatrixtest;
extern lv_group_t *btnmatrixgrp;
extern lv_obj_t *ui____initial_actions0;
extern lv_indev_t *indev_joystick;
extern const lv_style_t *btnmatrix_mainstyle;
extern const lv_style_t *btnmatrix_btnstyle;
extern const lv_style_const_prop_t *btnmatrix_mainstyle_props;
extern const lv_style_const_prop_t *btnmatrix_btnstyle_props;


LV_IMG_DECLARE( ui_img_1_bg_png);   // assets\1_bg.png
LV_IMG_DECLARE( ui_img_logo_png);   // assets\logo.png



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
