// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: UI_test

#ifndef _UI_COMP_INIT_BUTTON_H
#define _UI_COMP_INIT_BUTTON_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT init button
#define UI_COMP_INIT_BUTTON_INIT_BUTTON 0
#define UI_COMP_INIT_BUTTON_WELCOME_TEXT 1
#define _UI_COMP_INIT_BUTTON_NUM 2
lv_obj_t *ui_init_button_create(lv_obj_t *comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
