// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: UI_test

#include "../ui.h"

void ui_comp_init_button_create_hook( lv_obj_t * comp)
{
}
