// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: UI_test

#include "../ui.h"


// COMPONENT init button

lv_obj_t *ui_init_button_create(lv_obj_t *comp_parent) {

lv_obj_t *cui_init_button;
cui_init_button = lv_btn_create(comp_parent);
lv_obj_set_width( cui_init_button, 100);
lv_obj_set_height( cui_init_button, 22);
lv_obj_set_x( cui_init_button, 0 );
lv_obj_set_y( cui_init_button, 70 );
lv_obj_set_align( cui_init_button, LV_ALIGN_CENTER );
lv_obj_add_flag( cui_init_button, LV_OBJ_FLAG_CHECKABLE );   /// Flags
lv_obj_clear_flag( cui_init_button, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_bg_color(cui_init_button, lv_color_hex(0x3044FA), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_init_button, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(cui_init_button, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(cui_init_button, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(cui_init_button, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(cui_init_button, lv_color_hex(0x000AC2), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(cui_init_button, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_border_color(cui_init_button, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_border_opa(cui_init_button, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_border_width(cui_init_button, 3, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_border_side(cui_init_button, LV_BORDER_SIDE_FULL, LV_PART_MAIN| LV_STATE_PRESSED);

lv_obj_t *cui_welcome_text;
cui_welcome_text = lv_label_create(cui_init_button);
lv_obj_set_width( cui_welcome_text, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_welcome_text, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( cui_welcome_text, LV_ALIGN_CENTER );
lv_label_set_text(cui_welcome_text,"Welcome");

lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_INIT_BUTTON_NUM);
children[UI_COMP_INIT_BUTTON_INIT_BUTTON] = cui_init_button;
children[UI_COMP_INIT_BUTTON_WELCOME_TEXT] = cui_welcome_text;
lv_obj_add_event_cb(cui_init_button, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
lv_obj_add_event_cb(cui_init_button, del_component_child_event_cb, LV_EVENT_DELETE, children);
ui_comp_init_button_create_hook(cui_init_button);
return cui_init_button; 
}

